[package]
name = "kursa_darbs"
version = "0.1.0"
authors = ["shyrik13 <shyrik13@inbox.lv>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eval = "^0.4"
regex = "1"